### ISSUE TITLE
Integrate with automatically generated API docs

### ISSUE THREAD

**Issue by jmeas** [orbitjs/orbitjs.com#1]
Orbit's API docs are generated from inline comments using YUIDoc.

**Todo:**

- [x] Figure out a system for integrating the built docs into the www.

**Prior art:**

~~It seems like Ember's site pulls down the Ember source repository, then builds the docs, then merges them with the www. This might be a good build system to reference. [Source here.](https://github.com/emberjs/website/blob/master/Rakefile#L39)~~

I was wrong. It turns out that the repositories need to be installed next to one another as [the README describes here](https://github.com/emberjs/website/tree/59837b08c5bbcbe6579094e78c4f0d15d0139a17#api-documentation).

===

Notes to myself on Ember's build process:

- Ember Data uses YUIDoc. Orbit also uses YUIDoc.
- `YUIDoc` generates a `data.json` file that contains all of the data necessary to render the documentation
- Ember's website provides a command to build the Ember Data docs from within the website directory
- Once the website builds the Ember Data docs, it converts it to YML and stores it in the repository in the `data` directory
- ...to be continued

**Comment by jmeas** [comment]
The current plan has the following steps:

#### Set up (one time)

- Install the orbit.js project and orbitjs.com repositories in sibling directories.

  ```
  - orbit
    - orbitjs.com
    - orbit.js
  ```

#### Building the latest docs
- From within the `orbit.js` repository, run `yuidoc .` to build the latest docs
- Run a command from this repository (copies over files from src repo; prepares to serve them)
- Run `jekyll serve` to serve the site

===

This isn't **so** bad, I think, and is a few steps less than Ember's site since we're only bringing in a single external repo. What do you think @dgeb ?

**Comment by dgeb** [comment]
@jmeas seems good - just a couple questions:

* is this approach compatible with hosting on gh pages (#4) ?
* can we easily host other docs (such as those for ember-orbit) as long as the repos are all in sibling directories?

I think the answer to both is yes but want to confirm.

**Comment by jmeas** [comment]
> can we easily host other docs (such as those for ember-orbit) as long as the repos are all in sibling directories?

Yup. The process scales out pretty easily. Ember uses this same system to host the Ember.js core docs as well as the Ember data docs, for instance. We could add any number of repos we want to the hosted site.

> is this approach compatible with hosting on gh pages (#4) ?

I think so. There are a few tradeoffs, though. The big one is that we would be unable to `gitignore` the docs we pull in from the other repos. Consequently, commits between releases will have a bit of noise.

Once we pull in the docs, and confirm that they render correctly locally, pushing them to `gh-pages` would make them live.

If we were to host them elsewhere, we would be able to gitignore the docs but would then have to write up a deploy script.

**Comment by dgeb** [comment]
Thanks for confirming, @jmeas.

Another likely requirement is the need to host multiple versions of docs and allow the user to select between them (e.g. 1.0, 1.1, 2.0). Any thoughts on which approach would make this easiest?

**Comment by jmeas** [comment]
> Another likely requirement is the need to host multiple versions of docs and allow the user to select between them (e.g. 1.0, 1.1, 2.0).

Yup, absolutely.

> Any thoughts on which approach would make this easiest?

I'm not sure if either would be easier, actually. I think they might just be different.

With Github pages, we might just keep all versions checked into the repository. With external hosting, we might go with a system like...

- the default command builds and pushes just the latest docs.
- provide a command to backfill all docs (this would rarely, if ever, be used. only if we migrate servers, or something)
- provide a command to update a particular version of the docs

**Comment by jmeas** [comment]
I spent much time thinking about this over the course of the week (#7), and here's what I've come up with:

- Master branch is the development branch.
- A separate build task compiles Jekyll pages from the generated API docs file
- Those compiled pages are not checked into master
- Those compiled pages **are** checked into the `gh-pages` branch, which is the live site

**Comment by jmeas** [comment]
Done in https://github.com/orbitjs/orbitjs.com/pull/10
