### ISSUE TITLE
API Table of Contents

### ISSUE THREAD

**Issue by jmeas** [orbitjs/orbitjs.com#20]
Ember's table of contents is pretty intense. Namespaces, Modules, Classes...I'm not even sure what the distinction between Modules and Namespaces is, to be quite honest.

Maybe that makes sense for a large project like Ember, but for Orbit, I think opting for a simpler system is best.

The format I think would be best is:

```
- Orbit
  - Orbit.Thing
  - Orbit.OtherThing
  - Orbit.ThirdThing
- OC
  - OC.Whatever
  - OC.OtherThing
```

I think this should cover everything. Thoughts @dgeb ?

**Comment by dgeb** [comment]
Looks like the auto-generated docs for Orbit could definitely benefit from organization and simplification.

I think it's fine to group namespaces and classes together. I would understand a namespace to be an object used for organization, such as `Orbit` or `OC`, but not expected to be instantiated (unlike a class).

I think of modules as more about groupings for distribution. I'm not sure it's necessary to list them in the sidebar.

**Comment by jmeas** [comment]
Thanks for the input, @dgeb! I'm gonna go ahead with this structure, then. If we decide we need to add more things (like modules or separated namespaces), then it shouldn't be too hard to change in the future.

**Comment by dgeb** [comment]
Sounds good - thanks @jmeas!

**Comment by jmeas** [comment]
Here's an img showing the table of contents without any design applied to it. (sry 2x size because of retina display...). So it's ugly, but it shows the structure I was going for:

![](https://cldup.com/dl7INqRabc-3000x3000.png)

I'll prob. update it to sort the classes alphabetically.
