### ISSUE TITLE
Add ability to pull in latest YUIDocs from source repo

### ISSUE THREAD

**Issue by jmeas** [orbitjs/orbitjs.com#21]
There should be a Gulp task in this repo that:

1. Pulls down the latest version of orbit.js (in a sibling directory)
2. Builds the docs
3. Copies and pastes the data file to this repo

**Comment by dgeb** [comment]
Sounds good :+1:

**Comment by jmeas** [comment]
I'm modeling my approach off of Ember's solution, which can be seen [here](https://github.com/emberjs/website/blob/3fda654e33de56411c6f799bc9cd4021e2a11bef/Rakefile#L39-L64).

Instead of rake, I'll likely be using an all-JS solution to do this. This may change depending on the outcome of #24

**Comment by jmeas** [comment]
Done
