### ISSUE TITLE
"private/internal" attributes?

### ISSUE THREAD

**Issue by jmeas** [orbitjs/orbitjs.com#41]
Of course, JavaScript has no true notion of an attribute access control. Nevertheless, a common pattern exists where "private," or "internal" attributes are prefixed with an underscore. @dgeb, does Orbit have, or plan to use, attributes like this?

You can see that in the Emberjs docs, they offer the choice of public, protected, or private. From what I can tell, protected isn't used, private is prefixed with an underscore, and public is everything else.

If we do plan to use a system like this, then I'll go ahead and add a checkbox system to toggle 'em.

**Comment by dgeb** [comment]
@jmeas I have tried to document private members as such, and also prefix them with an underscore. I don't believe I've marked any members as protected (everything not private is public).

> If we do plan to use a system like this, then I'll go ahead and add a checkbox system to toggle 'em.

That's a really handy feature for docs. Thanks!

**Comment by jmeas** [comment]
Thanks for the info, @dgeb! I'm tracking this feature over at #43.
